### ISSUE TITLE
Building px.exe succeeds, but never starts, no output on powershell or cmd

### ISSUE THREAD

**Issue by rubin55** [genotrance/px#90] opened 2019-07-08 17:57 UTC
I've git clone'ed master of px, installed python 3.7.4rc2, have visual studio build tools installed and did a `build.bat` to build an executable in dist/.

However, when I run the executable, either in cmd.exe or in powershell.exe, I get no output. the process never keeps running either (verified with 'tasklist | findstr /i px').

I get no errors or warnings during build and no errors or warnings during run. Even --debug will not output a debug log (like px usually does).

**Comment by genotrance** [comment] 2019-07-08 18:39
Do you have pyinstaller?

`pip install pyinstaller`

**Comment by rubin55** [comment] 2019-07-08 22:09
Yes, I have that. px.exe is built, but does absolutely nothing.

**Comment by rubin55** [comment] 2019-07-09 19:38
No, `px --help` also returns nothing; I tried both with cmd.exe and powershell.exe.

**Comment by genotrance** [comment] 2019-07-10 05:21
I presume the binary posted online under releases works fine, but the one you created locally does not.

Some other ideas, does `python px.py` work? Might want to verify that all dependencies required by px are installed, though I'd expect Pyinstaller to complain if something is missing.

**Comment by rubin55** [comment] 2019-07-10 12:07
That's right, downloaded binary works fine, locally compiled one with pyinstaller does not work. I'll try and test direct py px.py invocation somewhere today!

**Comment by shyamrallapalli** [comment] 2020-02-27 20:28
you could build the executable using debug on and see what the issue is (turned debug on and windowed mode off - see below command)
```shell
pyinstaller --clean --noupx -d all -F -i px.ico px.py --hidden-import win32timezone --exclude-module win32ctypes
```

when you run built executable, it should give you an error (there is a lot of log messages)
For me it seems to be an issue with keyring

```shell
  _load_plugins()
  File "c:\test_px\env\lib\site-packages\keyring\backend.py", line 199, in _load_plugins
    entry_points = metadata.entry_points()['keyring.backends']
KeyError: 'keyring.backends'
```
based on this post https://github.com/jaraco/keyring/issues/324#issuecomment-587311049
it is the version of keyring you are using that may be the culprit

so i downgraded my keyring to 18.0.0 and it built fine for me and working as expected
```shell
keyring==18.0.1
PyInstaller==3.5
```

**Comment by genotrance** [comment] 2022-01-26 17:32
No updates on this in a while, closing for now. Considering I'm moving towards a source only release model, we might see this again.

**Closed by genotrance** 2022-01-26 17:32 UTC
