### ISSUE TITLE
Add Proxy-Connection: Keepalive Header for HTTP/1.0 requests

### ISSUE THREAD

**Issue by holgerreif** [genotrance/px#12] opened 2017-08-29 08:54 UTC
While testing against squid 3.5.27 (latest stable) I observed the following behaviour:
A client using HTTP/1.0 w/o a `Proxy-Connection: Keepalive` header cannot be authenticated with NTLM; a HTTP/1.0 with `Proxy-Connection: Keepalive` header is authenticated as well as a HTTP/1.1 client regardless of the header.

As far as my research indicates, this is a valid behaviour: HTTP/1.1 implies a connection keep alive and NTLM auth may require connection keep alive (esp. in order to keep challenge and response together if going through a load balancer).

A possible solution would be to add an option for px to send a `Proxy-Connection: keepalive` header regardless of client's request (or at least for HTTP/1.0 connections). 

Here are the test cases (latest stable curl 7.55.1):
```
# HTTP/1.0 w/ Proxy-Connection Header // working
curl --proxy 127.0.0.1:3128  -v -0 http://some.server.de 
# HTTP/1.1 w/o Proxy-Connection Header // working
curl --proxy 127.0.0.1:3128 --proxy-header Proxy-Connection: -v  http://some.server.de
# HTTP/1.0 w/o Proxy-Connection Header // failing
curl --proxy 127.0.0.1:3128 --proxy-header Proxy-Connection: -v -0 http://some.server.de
```

**Comment by genotrance** [comment] 2017-09-25 17:06
I can add this behavior fairly easily but I'm wondering if this is how cNTLM or NTLMaps work on behalf of HTTP/1.0 clients. I guess considering that Px is having the conversation with the NTLM server, it would have to keep the connection alive for the conversation to happen.

Also, curious if the client is expected to do anything special to close the connection and if Px needs to do that as well on behalf of the client.

**Comment by holgerreif** [comment] 2017-09-25 17:56
px itself closes the connection after it receives the response from real proxy. So it does not keep the connection open on behalf of the client.

Actually the sequence looks as follows:
```
#  proxy          px          client
1                     request
                      <------
2   request&keep-alive
        <------
3   ntlm challenge
        ------>
4   request&ntlm response
        ------>
5                     response
                      ------->
6  [ closing connection ]
```

**Comment by genotrance** [comment] 2018-01-09 20:28
So just to confirm, the code change required is as follows:-

```python
if connection == "HTTP/1.0" and keepAliveHeader == False:
   Send keep-alive on behalf of client
```

By the way, which HTTP client are you using that's using 1.0 without the header?

**Comment by genotrance** [comment] 2018-01-12 00:20
I've checked in a fix for this issue - can you please verify that it works as expected for you? I couldn't reproduce the failure with my NTLM proxy which didn't care that keep-alive was missing for an HTTP/1.0 client.

**Comment by genotrance** [comment] 2018-02-19 22:42
Just posted v0.3.0 so marking this as closed.

**Closed by genotrance** 2018-02-19 22:42 UTC
Labels: fixed, waiting
