### ISSUE TITLE
IPv6 connect support

### ISSUE THREAD

**Issue by grimly** [genotrance/px#168] opened 2022-09-15 12:30 UTC
Hello, 

Node resolves all local adresses (`127.0.0.1` and all aliases from the `hosts` file) to its IPv6 variant ( `::1` ).
The issue is that px does not accept IPv6 connections.

This may be tested with this following curl command, assuming the default px configuration :
```bash
curl -x 'http://[::1]:3128/' -vs 'https://www.github.com' -o /dev/null
```

**Comment by genotrance** [comment] 2022-09-29 02:09
This is similar to #98 - I don't have an IPv6 setup to add support at this time. Maybe someone can contribute a patch.

**Comment by genotrance** [comment] 2022-12-10 04:13
Closing as duplicate of #98.

**Closed by genotrance** 2022-12-10 04:13 UTC
