### ISSUE TITLE
Negotiate auth not working

### ISSUE THREAD

**Issue by harg** [genotrance/px#71] opened 2018-11-20 08:55 UTC
Thank you for your work on this project!

I'm trying to get PX to work behind my company proxy (McAfee Web Gateway).
I keep getting 407 errors.

Am-i missing something here?

OS: Windows 10 64bit

Command:

    all_proxy=127.0.0.1:5000  curl -I https://google.com/

px.ini :

    [proxy]
    server = <proxy_server>:8080
    listen = 127.0.0.1
    port = 5000
    gateway = 0
    hostonly = 0
    allow = *.*.*.*
    noproxy =
    useragent = Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
    [settings]
    workers = 2
    threads = 5
    idle = 30
    socktimeout = 20.0
    proxyreload = 60
    foreground = 1
    log = 1

Log :

    MainProcess: MainThread: 1542703476: verify_request: Client address: 127.0.0.1
    MainProcess: Thread_0: 1542703476: do_CONNECT: Entering
    MainProcess: Thread_0: 1542703476: do_transaction: Entering
    MainProcess: Thread_0: 1542703476: get_destination: google.com:443
    MainProcess: Thread_0: 1542703476: do_socket_connect: New connection: ('<proxy_server>', 8080)
    MainProcess: Thread_0: 1542703477: do_proxy_type: Searching proxy type
    MainProcess: Thread_0: 1542703477: do_socket: Entering
    MainProcess: Thread_0: 1542703477: do_socket: CONNECT google.com:443 HTTP/1.1
    MainProcess: Thread_0: 1542703477: do_socket: Sending Host: google.com:443
    MainProcess: Thread_0: 1542703477: do_socket: Sending User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
    MainProcess: Thread_0: 1542703477: do_socket: Sending Proxy-Connection: Keep-Alive
    MainProcess: Thread_0: 1542703477: do_socket: Reading response code
    MainProcess: Thread_0: 1542703477: do_socket: Response code: 407 True
    MainProcess: Thread_0: 1542703477: do_socket: Reading response headers
    MainProcess: Thread_0: 1542703477: do_socket: Received Date: Tue, 20 Nov 2018 08:44:37 GMT
    MainProcess: Thread_0: 1542703477: do_socket: Received Content-Type: text/html
    MainProcess: Thread_0: 1542703477: do_socket: Received Cache-Control: no-cache
    MainProcess: Thread_0: 1542703477: do_socket: Received Content-Length: 3925
    MainProcess: Thread_0: 1542703477: do_socket: Received Proxy-Connection: Keep-Alive
    MainProcess: Thread_0: 1542703477: do_socket: Received Proxy-Authenticate: sanitized (9)
    MainProcess: Thread_0: 1542703477: do_proxy_type: Auth mechanisms: Negotiate
    MainProcess: Thread_0: 1542703477: do_proxy_type: Selected: ('<proxy_server>', 8080): NEGOTIATE
    MainProcess: Thread_0: 1542703477: get_response_wkb: winkerberos SSPI
    MainProcess: Thread_0: 1542703477: fwd_data: Reading response data
    MainProcess: Thread_0: 1542703477: fwd_data: Content length 3925
    MainProcess: Thread_0: 1542703477: do_socket: Entering
    MainProcess: Thread_0: 1542703477: do_socket: CONNECT google.com:443 HTTP/1.1
    MainProcess: Thread_0: 1542703477: do_socket: Sending Host: google.com:443
    MainProcess: Thread_0: 1542703477: do_socket: Sending User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
    MainProcess: Thread_0: 1542703477: do_socket: Sending Proxy-Connection: Keep-Alive
    MainProcess: Thread_0: 1542703477: do_socket: Sending extra Proxy-Authorization: sanitized len(66)
    MainProcess: Thread_0: 1542703477: do_socket: Reading response code
    MainProcess: Thread_0: 1542703477: do_socket: Response code: 407 True
    MainProcess: Thread_0: 1542703477: do_socket: Reading response headers
    MainProcess: Thread_0: 1542703477: do_socket: Received Date: Tue, 20 Nov 2018 08:44:37 GMT
    MainProcess: Thread_0: 1542703477: do_socket: Received Content-Type: text/html
    MainProcess: Thread_0: 1542703477: do_socket: Received Cache-Control: no-cache
    MainProcess: Thread_0: 1542703477: do_socket: Received Content-Length: 3925
    MainProcess: Thread_0: 1542703477: do_socket: Received Proxy-Connection: Keep-Alive
    MainProcess: Thread_0: 1542703477: do_socket: Received Proxy-Authenticate: sanitized (9)
    MainProcess: Thread_0: 1542703477: do_transaction: Auth required
    MainProcess: Thread_0: 1542703477: do_transaction: Didn't get challenge, auth didn't work
    MainProcess: Thread_0: 1542703477: do_CONNECT: Error 407
    MainProcess: Thread_0: 1542703477: log_message: code 407, message Proxy Authentication Required
    MainProcess: Thread_0: 1542703477: log_message: "CONNECT google.com:443 HTTP/1.1" 407 -
    MainProcess: Thread_0: 1542703477: do_CONNECT: Cleanup proxy connection
    MainProcess: Thread_0: 1542703477: do_CONNECT: 0 bytes read, 0 bytes written
    MainProcess: Thread_0: 1542703477: do_CONNECT: Done

**Comment by genotrance** [comment] 2018-11-20 20:10
Looks like the proxy returns Negotiate so Px uses winkerberos. It's possible that using NTLM might be better in this case but no way to force it yet. I'll have to add a setting to force Px to use NTLM and see if it works.

You could try editing [px.py](https://github.com/genotrance/px/blob/master/px.py#L346) and force NTLM and see if it works for you. Curious - if it does, we could enhance Px to handle this better.

**Comment by seandwyer** [comment] 2018-11-21 16:32
Hi Guys, I had same problem. I've fixed it in the code (in do_transaction) where the Auth is being sent. Bascially, what happens is that theres a Connection:Close header sent, which closes the response (in do_socket), before it has a chance to get the Auth from the server response. I've simply changed the Connection:Close header if exists, to Connection: Keep-Alive, OR add new one to xheaders if not:

              # Send auth message
                conn_found = False
                for header in self.headers:
                    if header[0] == "Connection":
                        header[1] = "Keep-Alive"
                        conn_found = True
                        break

                if not conn_found:                                  
                    resp = self.do_socket(
                       { "Proxy-Authorization": "%s %s" % (proxy_type, ntlm_resp),"Connection": "Keep-Alive" } )
                else:
                    resp = self.do_socket({
                        "Proxy-Authorization": "%s %s" % (proxy_type, ntlm_resp)})

Hope this helps.

Regards,
Sean

**Comment by seandwyer** [comment] 2018-11-21 16:33
GREAT, GREAT project, by the way! Excellent job!

**Comment by genotrance** [comment] 2019-03-06 17:01
This is similar to https://github.com/genotrance/px/issues/73.

**Comment by martin-s** [comment] 2019-05-03 02:42
I had trouble with NTLM auth. And the fix by @seandwyer didn't help either.

A fix was to use NEGOTIATE (both: NTLM and NEGOTIATE are supported by the proxy). As NEGOTIATE is the first of the two, it should be used first, IMO. There should be a break in https://github.com/genotrance/px/blob/3f03957b7f108a6c2cef68c0af40a9c775aa1609/px.py#L617 after every auth mechanism, so that the first one is used.
px could also try both, if more than one are defined.

**Comment by seandwyer** [comment] 2019-05-03 07:30
@martin-s 
I've recently discovered that my fix doesn't get the correct self.headers. So, i've simply always added the Connection Keep-Alive tuple to the xheaders parameter for the do_socket call, and this fixes the scenario for me. I hope it will do the same for you. Remove all the conn_found stuff, and add the header to all calls.

resp = self.do_socket({ "Proxy-Authorization": "%s %s" % (proxy_type, ntlm_resp),"Connection": "Keep-Alive" } )

**Comment by martin-s** [comment] 2019-05-03 09:58
@seandwyer 
No, unfortunately NTLM handhshake is not working.
Header are set, as you proposed and socket connection is always on keep-alive. I see two places in px.py where this happens. Right?

**Comment by btsimonh** [comment] 2019-05-10 08:27
Same issue here with release version;
My biggest issue was testing against WinGate with browser going through Wingate as well - it cached credentials for my IP (127.0.0.1 in this case), and so hardly ever asked for authorisation, and so 'seemed' to work.  Now I have cleared the cache, and only have one app running though, it never authenticates, and sends Wingate's 'you must authenticate' body back for every GET/POST.

I have not applied any of the above 'fixes' or looked at the code :( (yet).

log of first couple of transactions:
```
MainProcess: MainThread: 1557475374: verify_request: Client address: 127.0.0.1
MainProcess: Thread_0: 1557475374: do_GET: Entering
MainProcess: Thread_0: 1557475374: do_GET: Path = https://xxxxx.tv/image/devicedetail?deviceid=6680
MainProcess: Thread_0: 1557475374: do_transaction: Entering
MainProcess: Thread_0: 1557475374: get_destination: nebula.yella.tv:443
MainProcess: Thread_0: 1557475374: get_destination: https://xxxxx.tv/image/devicedetail?deviceid=6680 => ('xxxxx', 443) + /image/devicedetail?deviceid=6680
MainProcess: Thread_0: 1557475374: do_socket_connect: New connection: ('127.0.0.1', 8443)
MainProcess: Thread_0: 1557475374: do_proxy_type: Searching proxy type
MainProcess: Thread_0: 1557475374: do_socket: Entering
MainProcess: Thread_0: 1557475374: do_socket: GET https://xxxxx.tv/image/devicedetail?deviceid=6680 HTTP/1.1
MainProcess: Thread_0: 1557475374: do_socket: Sending Authorization: Bearer xxxxx
MainProcess: Thread_0: 1557475374: do_socket: Sending Host: xxxxx.tv
MainProcess: Thread_0: 1557475374: do_socket: Sending Connection: close
MainProcess: Thread_0: 1557475374: do_socket: Reading response code
MainProcess: Thread_0: 1557475374: do_socket: Response code: 407 True
MainProcess: Thread_0: 1557475374: do_socket: Reading response headers
MainProcess: Thread_0: 1557475374: do_socket: Received Proxy-Authenticate: sanitized (9)
MainProcess: Thread_0: 1557475374: do_socket: Received Proxy-Authenticate: sanitized (4)
MainProcess: Thread_0: 1557475374: do_socket: Received Proxy-Authenticate: sanitized (32)
MainProcess: Thread_0: 1557475374: do_socket: Received Proxy-Support: session-based-authentication
MainProcess: Thread_0: 1557475374: do_socket: Received Cache-control: no-store, no-cache
MainProcess: Thread_0: 1557475374: do_socket: Received Content-Type: text/html; charset=utf-8
MainProcess: Thread_0: 1557475374: do_socket: Received Content-Length: 855
MainProcess: Thread_0: 1557475374: do_socket: Received Date: Fri, 10 May 2019 08:02:54 GMT
MainProcess: Thread_0: 1557475374: do_socket: Received Server: WinGate Engine
MainProcess: Thread_0: 1557475374: do_socket: Received Connection: Close
MainProcess: Thread_0: 1557475374: do_proxy_type: Auth mechanisms: Negotiate NTLM Basic realm="/", charset="UTF-8"
MainProcess: Thread_0: 1557475374: do_proxy_type: Selected: ('127.0.0.1', 8443): NTLM
MainProcess: Thread_0: 1557475374: get_response_sspi: pywin32 SSPI
MainProcess: Thread_0: 1557475374: fwd_data: Reading response data
MainProcess: Thread_0: 1557475374: fwd_data: Content length 855
MainProcess: Thread_0: 1557475374: fwd_data: Close proxy connection per header
MainProcess: Thread_0: 1557475374: do_socket: Entering
MainProcess: Thread_0: 1557475374: do_socket_connect: New connection: ('127.0.0.1', 8443)
MainProcess: Thread_0: 1557475374: do_socket: GET https://xxxxx.tv/image/devicedetail?deviceid=6680 HTTP/1.1
MainProcess: Thread_0: 1557475374: do_socket: Sending Authorization: Bearer xxxxx
MainProcess: Thread_0: 1557475374: do_socket: Sending Host: xxxxx.tv
MainProcess: Thread_0: 1557475374: do_socket: Sending Connection: close
MainProcess: Thread_0: 1557475374: do_socket: Sending extra Proxy-Authorization: sanitized len(81)
MainProcess: Thread_0: 1557475374: do_socket: Reading response code
MainProcess: Thread_0: 1557475374: do_socket: Response code: 407 True
MainProcess: Thread_0: 1557475374: do_socket: Reading response headers
MainProcess: Thread_0: 1557475374: do_socket: Received Proxy-Authenticate: sanitized (229)
MainProcess: Thread_0: 1557475374: do_socket: Received Cache-control: no-store, no-cache
MainProcess: Thread_0: 1557475374: do_socket: Received Content-Type: text/html; charset=utf-8
MainProcess: Thread_0: 1557475374: do_socket: Received Content-Length: 855
MainProcess: Thread_0: 1557475374: do_socket: Received Date: Fri, 10 May 2019 08:02:54 GMT
MainProcess: Thread_0: 1557475374: do_socket: Received Server: WinGate Engine
MainProcess: Thread_0: 1557475374: do_socket: Received Connection: Close
MainProcess: Thread_0: 1557475374: do_transaction: Auth required
MainProcess: Thread_0: 1557475374: do_transaction: Challenged
MainProcess: Thread_0: 1557475374: get_response_sspi: pywin32 SSPI
MainProcess: Thread_0: 1557475374: fwd_data: Reading response data
MainProcess: Thread_0: 1557475374: fwd_data: Content length 855
MainProcess: Thread_0: 1557475374: fwd_data: Close proxy connection per header
```

**Comment by btsimonh** [comment] 2019-05-10 11:53
ok; doing some investigation.
My situation is that 'connection: close' is in ALL my requests (from nodejs).
The 'connection: close' is passed through px to the WinGate proxy, which includes it in the response headers.  This causes px to close the connection.  This seems a bad thing to do in the authorisation phase...
If I just "don't close" the connection during negotiation, I find that Wingate has closed the connection.
If i replace my 'connection: close' with 'connection: keep-alive' for every request, it manages to do the authentication.
So...  I will attempt to:
leave the 'connection: close' in place for each first message (since wingate may not require authorisation if cached).  If the response is 407, then change it to keep-alive for the authorisation exchange, then restore it to initial value for the final part (where data is forwarded).
Will ping back if it works....

(found [this](https://jdebp.eu/FGA/web-proxy-connection-header.html) which states 'connection: is a single hop header, so will try just discarding it...).
......
Some time later:
I'll issue a PR for removing the connection headers from received requests.  Seems to work, but will need a review because 1/ I don't do python 2/ I'm no HTTP and proxy expert.

**Comment by btsimonh** [comment] 2019-05-10 18:09
my PR is ready https://github.com/genotrance/px/pull/85

**Comment by genotrance** [comment] 2019-05-18 04:32
Took a while to figure it out but here's actually three different issues in this one issue.

Issue 1 from @harg originally is that proxy returns Negotiate but it really means NTLM. Using winkerberos for Negotiate isn't working. Simple fix is to allow specifying proxy type in the ini file but puts the burden on the user to figure this out. Ideally, px should try winkerberos and then pywin32 and then give up. Still, adding a flag in the ini file doesn't hurt, at least the user can test without having to debug code. Basically, we need a fix for #73 and a retry with the other auth protocol.

Issue 2 from @martin-s is that px should pick the first auth mechanism rather than NTLM as first if it is anywhere in the string. Either proxies misrepresent what they are really capable of or who knows what's really going on there. Fix for this is to go in order. Fix for issue 1 will also help since it will fall back to NTLM on the retry and users can always experiment with proxy type in the ini file to see if it helps.

Issue 3 is what @seandwyer and @btsimonh have reported - for whatever reason, the proxy is closing the connection due to the `Connection: close` header. It really shouldn't even look at that header since there's a separate `Proxy-Connection` header. However, HTTP is really open to interpretation so looks like switching to `keep-alive`, at least for authorization makes sense. Globally setting `keep-alive` doesn't serve us since it conflicts with when the client really wants to close the connection so I'll adapt a variation of @btsimonh's PR #85.

I appreciate all the reports and the patience, and will sincerely appreciate a test of the new code since there's no way for me to test if any of this really works as expected. It is part of the reason I'm seriously considering switching to libcurl as the backend given it does all this NTLM/Kerberos nonsense itself and is the best when it comes to HTTP.

**Comment by btsimonh** [comment] 2019-05-18 06:40
:) yes, testing is horrific.  First my final proxy hid everything from me by just saying 'I saw your IP authorise (the browser), so you don't need to' - so making me think everything was rosy...  then there's my code sending 'connection: close'; probably something which is not necessarily normal; then there is the variety of authorization requirements, and finally a lack of very firm specification, and the number of different implementations of downstream proxies.

However, I cannot change my client software - it's difficult enough to make sure all the http(s) client connections implement the proxy configuration in nodejs :( - and this is the best (and only) implementation that I found which did anything like this, so your efforts are very much appreciated.
One option for me would be to port it all to node as a proxy agent, but the access to the windows security layer for use as a client is just not available (there is a project which does this as a server...).

I can test against Wingate (as much as I understand it), and also should be able to get my customer to test against proxysg (with their unknown configuration).
Note: I have modified most of my client code to ALWAYS use CONNECT (mainly because else it sends a lot in the clear for HTTPS if using HTTP proxying, but also because then px is exercised the same every time, easier for me to trace & understand).  BUT, it does seem to be challenged more often (every connection?), so I wonder if the proxy auth data sent on subsequent calls is correct?

**Comment by genotrance** [comment] 2019-05-18 06:53
@btsimonh - so I will be porting your fix into Px, we will make sure that connection is not closed during auth. The testing will be required on your part to confirm I got it right but @seandwyer will have to check as well to see if it resolves his use case.

**Comment by genotrance** [comment] 2019-05-20 02:17
Issue 1 and 2 are both party fixed since auth mechanism can now be picked in the [INI file](https://github.com/genotrance/px/blob/master/px.ini#L61). @harg and @martin-s please confirm if this helps your situation. I am still looking into picking first mechanism and failover functionality.

Issue 3 should also be fixed in https://github.com/genotrance/px/commit/3bae3f8a6ba5af07c7d37ee0e7d2a1af910ae134. @btsimonh and @seandwyer please confirm if it works as expected. Thanks to @btsimonh for his PR #85.

**Comment by btsimonh** [comment] 2019-05-20 10:26
Explains wingate & only asking for auth once:
https://serverfault.com/questions/811648/why-is-only-the-first-request-to-an-ntlm-authenticating-proxy-challenged-and-how
I did manage to disable credential caching for testing with this:
![image](https://user-images.githubusercontent.com/3137332/58014982-053bf300-7af2-11e9-980b-178bf7852f32.png)

But... see next comment:

**Comment by seandwyer** [comment] 2019-05-20 11:36
Hi guys,
Unfortunately, the new remove header code in do_transaction, doesn't seem to execute. So, my connection keeps getting closed, as before. The only solution that works for me is to add the Connection: Keep-Alive to the xheaders of the do_socket call, shown here:

                hconnection = ""
                for i in ["connection", "Connection"]:
                    if i in self.headers:
                        hconnection = self.headers[i]
                        del self.headers[i]
                        dprint("Remove header %s: %s" % (i, hconnection))

                # Send auth message
                resp = self.do_socket({
                    "Proxy-Authorization": "%s %s" % (proxy_type, ntlm_resp), **"Connection": "Keep-Alive"** 
                })

Thanks,
Sean

**Comment by genotrance** [comment] 2019-05-20 16:17
@seandwyer - can you please share a px debug log of your failure? Is your client doing an HTTP/1.0 request by any chance?

**Comment by btsimonh** [comment] 2019-05-20 16:20
@seandwyer - I see no reason not to add this in that one location; maybe the next proxy needs the keep-alive in your case.
Q: Is there a 'connect: close' in your original request? - i.e. is the above code not working, or is it already not there, but the lack of keep-alive the issue?
Log (attached) of working HTTP connection where 'connection: close' is removed and restored (using Negotiate):

[HTTPconnectionclose.txt](https://github.com/genotrance/px/files/3198043/HTTPconnectionclose.txt)

Also tested with NTLM, and CONNECT.

**Comment by btsimonh** [comment] 2019-05-20 16:25
p.s. also added the extra keep-alive, and so far so good - it does to seem to break anything *in my limited case*.  Found broken things in my client (like trying to CONNECT to www.google.co.uk:443 for HTTP); but that's a whole nodejs story :).

**Comment by genotrance** [comment] 2019-05-20 17:28
I've added a fix for issue 2 (auth mechanism in order) as well as the keep-alive workaround during auth in https://github.com/genotrance/px/commit/d196d2ad66e3b3ee84b429f54c7bb283562389c0. Please confirm Px works for these scenarios correctly.

@seandwyer - still hoping you can check if your client is using HTTP/1.0 since the keep-alive fix would be done in do_socket() instead as a general fix.

Only thing that remains is to retry with other mechanism as a fallback before giving up.

**Comment by seandwyer** [comment] 2019-05-21 08:12
Hi,
using HTTP/1.1 - from wget on Ubuntu server virtual machine (on VirtualBox).
Added log files. the added keepalive is on do_socket call in do_transaction, as per previous email.

[20190521-debug-with-added-KeepAlive.log](https://github.com/genotrance/px/files/3201413/20190521-debug-with-added-KeepAlive.log)
[20190521-debug.log](https://github.com/genotrance/px/files/3201414/20190521-debug.log)

**Comment by btsimonh** [comment] 2019-05-21 08:56
note on this page:
https://bugs.chromium.org/p/chromium/issues/detail?id=8771
```
I was going to submit a bug report to Squid, so I first searched
existing bug reports for this issue.

http://www.squid-cache.org/bugs/show_bug.cgi?id=928
http://www.squid-cache.org/bugs/show_bug.cgi?id=1447
http://www.squid-cache.org/bugs/show_bug.cgi?id=2022

The last bug report (2022) is the shortest and the most relevant to us.
Anyway, while reading through the bugs, I noticed one thing:

All of the clients affected by this bug (Chromium, Apache-HttpClient,
and Java) send HTTP/1.1 CONNECT requests *without* a
"Proxy-Connection: keep-alive" header

This, and the fact that Squid seems to be an HTTP/1.0 proxy, can explain
why Squid sends "Proxy-Connection: close" to these clients.

I will look up the HTTP CONNECT request headers that Firefox and IE send
when I get to work.  Darin, I remember we discussed this issue when I
implemented HTTP CONNECT, and it was my fault to omit the
"Proxy-Connection: keep-alive" header.
```
note the last references quid bug report is now here:
https://bugs.squid-cache.org/show_bug.cgi?id=2022
and explains what we need and why.

and
https://src.chromium.org/viewvc/chrome/trunk/src/net/http/http_network_transaction.cc?r1=17761&r2=17760

Seems the chromium team thought 'Proxy-Connection: keep-alive' was appropriate in 2009; 
@seandwyer - can you test with 'Proxy-Connection: keep-alive' instead to confirm if this works with your squid?
Really could do with a wireshark of what chromium does now - source of http_network_transaction.cc is completely rewritten.

**Comment by seandwyer** [comment] 2019-05-21 10:53
Excellent deduction, @btsimonh! That's the solution! 
I put 'Proxy-Connection: Keep-Alive' in the headers do_socket call (in do_transaction):

                # Send auth message
                resp = self.do_socket({
                    "Proxy-Authorization": "%s %s" % (proxy_type, ntlm_resp), "Proxy-Connection": "Keep-Alive" 
                })

**Comment by martin-s** [comment] 2019-05-21 21:57
I can confirm that issue 2 is fixed for my environment.

**Comment by genotrance** [comment] 2019-05-22 12:50
Thanks for verifying everyone.

Px already forces `Proxy-Connection: Keep-Alive` for HTTP/1.0 in `do_socket()`. But it won't work in @seandwyer's scenario. I'll change `Connection` to `Proxy-Connection` here:

https://github.com/genotrance/px/blob/master/px.py#L745

Looks like only other thing that remains is to failover.

**Comment by andreaswittig** [comment] 2019-07-31 11:26
Run into the same problem with a Node.js application. The latest fix from @genotrance fixed the problem. Thanks!

**Comment by guillp** [comment] 2020-12-21 08:49
I also ran into this issue since a few days in my organization. I compiled an updated px.exe including that fix and it works.
Maybe you could make an official release with this fix?

**Comment by genotrance** [comment] 2022-06-04 20:26
Px now relies on libcurl for proxy auth so this might no longer be needed.

**Closed by genotrance** 2022-06-04 20:26 UTC
Labels: enhancement
