### ISSUE TITLE
Support for NTLM V2

### ISSUE THREAD

**Issue by sankethpb** [genotrance/px#13] opened 2017-11-03 09:32 UTC
Currently while using px with ntlmv2 proxy server we get error from curl commands that `"Your credentials could not be authenticated: "Another round of authentication required.". You will not be permitted access until your credentials can be verified.`
Does it support NTLMV2 auth for proxy server?

**Comment by genotrance** [comment] 2017-11-03 15:53
Can you please run Px in debug mode and attach the logs as well as the curl command line output?

**Comment by sankethpb** [comment] 2017-11-09 07:37
OS: Win 10 / Win 7 64bit
Commands:
````
SET HTTP_PROXY=http://localhost:3129/
SET HTTPS_PROXY=http://localhost:3129/
curl -u user:password -X PUT http://server_url:8081/artifactory/BuildArtifacts/Sample_Installer/Sample_Installer_1.0.0.16.zip -T "C:\Sample_Installer_1.0.0.15.zip"
````
here 'user' and 'password' is login required for http://server_url...

Log:
````
Serving at 127.0.0.1:3129 proc MainProcess
MainProcess: Thread-1: 1510211822: do_PUT: Entering
MainProcess: Thread-1: 1510211822: do_GET: Entering
MainProcess: Thread-1: 1510211822: do_transaction: Entering
MainProcess: Thread-1: 1510211822: do_socket: Entering
MainProcess: Thread-1: 1510211822: do_socket: New connection
MainProcess: Thread-1: 1510211822: do_socket: b'PUT 
http://server_url:8081/artifactory/BuildArtifacts/Sample_Installer/Sample_Installer_1.0.0.16.zip HTTP/1.1\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'Host: server_url:8081\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'Authorization: Basic dXNlcjpnZW5lc2lzU2VydmljZQ==\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'User-Agent: curl/7.56.1\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'Accept: */*\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'Proxy-Connection: Keep-Alive\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'Content-Length: 3894166\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending b'Expect: 100-continue\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Sending extra b'Proxy-Authorization: NTLM TlRMTVNTUAABAAAAB7IIogQABAAyAAAACgAKACgAAAAKANc6AAAAD0JNSDEwNzM2NDRBUEFD\r\n'
MainProcess: Thread-1: 1510211822: do_socket: Getting body for POST/PUT/PATCH
MainProcess: Thread-1: 1510211823: do_socket: Sending body for POST/PUT/PATCH
MainProcess: Thread-1: 1510211824: do_socket: Reading response code
MainProcess: Thread-1: 1510211824: do_socket: Response code: 100 False
MainProcess: Thread-1: 1510211824: do_socket: Reading response headers
MainProcess: Thread-1: 1510211824: do_socket: Reading response data
MainProcess: Thread-1: 1510211824: do_socket: Not sure how much
MainProcess: Thread-1: 1510211955: do_transaction: No auth required
MainProcess: Thread-1: 1510211955: fwd_resp: Entering
127.0.0.1 - - [09/Nov/2017 12:49:15] "PUT http://server_url:8081/artifactory/BuildArtifacts/Sample_Installer/Sample_Installer_1.0.0.16.zip HTTP/1.1" 100 -
MainProcess: Thread-1: 1510211955: fwd_resp: Done
MainProcess: Thread-1: 1510211955: do_GET: Done
MainProcess: Thread-1: 1510211955: do_PUT: Done
````

ini file:
````
[proxy]

; NTLM server to connect through
;   If omitted, Px will exit immediately
;   IP:port
;   Hostname:port
server = company.proxy.com:8080

; IP interface to listen on - default: 127.0.0.1
listen = 127.0.0.1

; Port to run this proxy on - default: 3128
port = 3129

; Allow remote machines to use this proxy
;   Overrides listen definition above and binds to all interfaces
gateway = 0

; Direct connect to following subnets, comma separated
;   Skip the NTLM proxy and connect directly like a regular proxy
;   192.168.0.* - wildcards
;   192.168.0.1-192.168.0.255 - ranges
;   192.168.0.1/24 - CIDR
noproxy =

[settings]

; Number of parallel workers (processes)
workers = 3

; Number of parallel threads per worker (process)
threads = 5

; Idle timeout in seconds for HTTP connect sessions before closing the connection
idle = 30

; Enable logging
log = 1

````
@genotrance please find the requested information above. our proxy server uses ntlmv2 auth.

**Comment by genotrance** [comment] 2017-11-10 05:12
This looks like an issue with HTTP PUT + Expect: 100-continue. I don't think Px supports this yet and I need to figure out how to handle it correctly.

What's also interesting is that your NTLM proxy returns the 100 continue response back without actually challenging Px for authorization. This just might be because of Px not handling the 100 correctly in the first place. I've at least reproduced the issue so might have something useful soon.

**Comment by sankethpb** [comment] 2017-11-16 09:22
@genotrance Thank you, a fix to this would be great to have.

**Comment by genotrance** [comment] 2018-01-12 00:21
I've checked in a fix for this issue - can you please verify that it works as expected for you? I verified it against a dummy PUT endpoint so a real world test will be very beneficial.

**Comment by genotrance** [comment] 2018-02-19 22:42
Just posted v0.3.0 so marking this as closed.

**Closed by genotrance** 2018-02-19 22:42 UTC
Labels: fixed, waiting
