### ISSUE TITLE
px 0.8.4: PAC configuration seems to cause unstable behaviour

### ISSUE THREAD

**Issue by pauko** [genotrance/px#198] opened 2023-11-15 09:23 UTC
Hello community!

I'm using px version 0.8.4. on a Windows host with `hostonly` and `gateway` options, as I want processes running in WSL2 to use that local proxy to communicate with "the outer world" via the corporate proxy server. Additionally, i set the URL of the PAC file in the `pac` field of `px.ini`.

I see considerable stability issues with this setup. Out of a sudden, the `px` processes on Windows terminate without any visible indication of a crash, neither on the command line nor in the log files, which I let it write with `log=1` in `px.ini`. It's quite reproducible when running some `npm install ...` inside WSL2.

However, if I give the URL of the corporate proxy in the `server` field instead of the PAC file in `pac`, `px` seems to run smoothly.

Additional information, maybe relevant:
I have to run [wsl-vpnkit](https://github.com/sakai135/wsl-vpnkit) in the [standalone script setup](https://github.com/sakai135/wsl-vpnkit#setup-as-a-standalone-script) with ["autostart by systemd"](https://github.com/sakai135/wsl-vpnkit#setup-systemd) inside the WSL2 distribution.

As said above, I don't find any error messages or crash dumps in the log files, but maybe `px` leaves some interesting information somewhere else. If somebody tells me, how to retrieve such information (if existing), I can append it to this report!

**Comment by Torsten4BoschBTHildesheim** [comment] 2024-02-13 08:55
Same with px 0.9 (windows)

But maybe I have some more debug info. I get the following message in the command line window:

Assertion failed: !runtime_data->thread_state, file module.c, line 83

**Comment by genotrance** [comment] 2024-02-14 16:10
Looks like this is basically a duplicate of #206. Thanks for the reports - I'll figure this out for v0.9.1.

**Comment by genotrance** [comment] 2024-02-22 15:03
Fixed in [v091](https://github.com/genotrance/px/tree/v091).

**Closed** 2024-03-02 02:00 UTC
Labels: bug, fixed

**Comment by genotrance** [comment] 2024-03-02 02:12
[v0.9.1](https://github.com/genotrance/px/releases/tag/v0.9.1) has been released.
